# This is a basic workflow to help you get started with Actions

name: Move new requests to the general Open Mainframe Project Kanban Board

on: [issues, pull_request]
jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-organization-based-project-column
      uses: takanabe/github-actions-automate-projects@v0.0.2
      if: ( github.event_name == 'issues' || github.event_name == 'pull_request' ) && github.event.action == 'opened' && !contains(github.event.issue.labels.*.name,'zowe-blog') && !contains(github.event.issue.labels.*.name,'podcast')
      env:
        GITHUB_TOKEN: ${{ secrets.YOUR_NEW_PERSONAL_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/openmainframeproject/projects/3 # update each quarter
        GITHUB_PROJECT_COLUMN_NAME: To Do
