name: Update Data From LFX
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: jmertic/lfx-tac-actions@3cc53bcc460908d9a414290e83e8104357b0d652 # 20260908
        with:
          updateprojects: false
          updatetacmembers: false
          updatetacagendaitems: false
          updateclomonitor: false
          updateartwork: true
          slug: open-mainframe-project
        env:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ steps.app-token.outputs.token }}
