name: Update Data From LFX
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jmertic/lfx-tac-actions@2682b048da24d3046b4c4b1959bbc3723666b635 # 20260826
        with:
          updateprojects: false
          updatetacmembers: false
          updatetacagendaitems: false
          updateclomonitor: false
          updateartwork: true
          slug: open-mainframe-project
        env:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
