name: Update Data From LFX
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jmertic/lfx-tac-actions@3cc53bcc460908d9a414290e83e8104357b0d652 # 20260908
        with:
          updateprojects: false
          updatetacmembers: false
          updatetacagendaitems: false
          updateclomonitor: false
          updateartwork: true
          slug: open-mainframe-project
        env:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
